window.PANZER_CATALOGO = {
  "sedes": [
    "Kemilabo",
    "Bolivariana",
    "Toberín",
    "Bello",
    "San Felipe",
    "Perdomo"
  ],
  "productos": [
    {
      "handle": "autolavado-12-de-octubre",
      "ref": "10035",
      "nombre": "AUTOLAVADO 12 DE OCTUBRE",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "autolavado-aeropuerto-1",
      "ref": "10033",
      "nombre": "AUTOLAVADO AEROPUERTO",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "autolavado-bello",
      "ref": "10085",
      "nombre": "AUTOLAVADO BELLO",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "autolavado-bolivariana",
      "ref": "10025",
      "nombre": "AUTOLAVADO BOLIVARIANA",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "autolavado-chía",
      "ref": "10036",
      "nombre": "AUTOLAVADO CHÍA",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "autolavado-itagui-1",
      "ref": "10002",
      "nombre": "AUTOLAVADO ITAGUI",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "autolavado-la-bayadera",
      "ref": "10027",
      "nombre": "AUTOLAVADO LA BAYADERA",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "autolavado-la-union",
      "ref": "10026",
      "nombre": "AUTOLAVADO LA UNION",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "autolavado-marly",
      "ref": "10032",
      "nombre": "Autolavado marly",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "autolavado-perdomo",
      "ref": "10048",
      "nombre": "AUTOLAVADO PERDOMO",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "autolavado-rionegro-1",
      "ref": "10037",
      "nombre": "AUTOLAVADO RIONEGRO",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "autolavado-san-felipe",
      "ref": "10046",
      "nombre": "AUTOLAVADO SAN FELIPE",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "autolavado-toberin-bogota",
      "ref": "10023",
      "nombre": "AUTOLAVADO TOBERIN",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "bebida-de-4000",
      "ref": "10000",
      "nombre": "BEBIDA LITRO 7.000",
      "categoria": "SNACKS",
      "tipo": "producto",
      "precio": 7000,
      "precio_variable": false,
      "costo": 3152,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": -56,
        "Toberín": -6,
        "Bello": 12,
        "San Felipe": -5,
        "Perdomo": 0
      }
    },
    {
      "handle": "bebidas-1800",
      "ref": "10086",
      "nombre": "BEBIDAS 2500",
      "categoria": "SNACKS",
      "tipo": "producto",
      "precio": 2500,
      "precio_variable": false,
      "costo": 1270,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": -23,
        "Toberín": -27,
        "Bello": 35,
        "San Felipe": -28,
        "Perdomo": 0
      }
    },
    {
      "handle": "bebidas-2800",
      "ref": "10087",
      "nombre": "BEBIDAS 3500",
      "categoria": "SNACKS",
      "tipo": "producto",
      "precio": 3500,
      "precio_variable": false,
      "costo": 1680,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": -77,
        "Toberín": -32,
        "Bello": 53,
        "San Felipe": -81,
        "Perdomo": 0
      }
    },
    {
      "handle": "bebidas-3800",
      "ref": "10088",
      "nombre": "BEBIDAS 4500 POWERADE,GATORADE ETC...",
      "categoria": "SNACKS",
      "tipo": "producto",
      "precio": 4500,
      "precio_variable": false,
      "costo": 2100,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": -3,
        "Toberín": 0,
        "Bello": 5,
        "San Felipe": -12,
        "Perdomo": 0
      }
    },
    {
      "handle": "blood-wheel-clean",
      "ref": "10021",
      "nombre": "BLOOD WHEEL CLEAN",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 25000,
      "precio_variable": false,
      "costo": 7844,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": 1,
        "Toberín": 2,
        "Bello": 7,
        "San Felipe": 1,
        "Perdomo": -2
      }
    },
    {
      "handle": "blood-wheel-clean-250-ml",
      "ref": "10024",
      "nombre": "BLOOD WHEEL CLEAN 250 ML",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 18000,
      "precio_variable": false,
      "costo": 4665,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": 10,
        "Toberín": 12,
        "Bello": 10,
        "San Felipe": 4,
        "Perdomo": 1
      }
    },
    {
      "handle": "cepillo-de-mano",
      "ref": "10010",
      "nombre": "CEPILLO DE MANO",
      "categoria": "PRODUCTOS COMPLEMENTARIOS DE LAVADO",
      "tipo": "producto",
      "precio": 3500,
      "precio_variable": false,
      "costo": 1833,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": -1,
        "Toberín": 9,
        "Bello": 5,
        "San Felipe": 3,
        "Perdomo": 3
      }
    },
    {
      "handle": "cepillo-escoba",
      "ref": "10015",
      "nombre": "CEPILLO ESCOBA",
      "categoria": "PRODUCTOS COMPLEMENTARIOS DE LAVADO",
      "tipo": "producto",
      "precio": 14500,
      "precio_variable": false,
      "costo": 10000,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": -1,
        "Toberín": -2,
        "Bello": 0,
        "San Felipe": -5,
        "Perdomo": 4
      }
    },
    {
      "handle": "cepillo-llantas",
      "ref": "10047",
      "nombre": "CEPILLO LLANTAS",
      "categoria": "PRODUCTOS COMPLEMENTARIOS DE LAVADO",
      "tipo": "producto",
      "precio": 4500,
      "precio_variable": false,
      "costo": 3000,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": -1,
        "Toberín": -6,
        "Bello": 3,
        "San Felipe": -8,
        "Perdomo": 5
      }
    },
    {
      "handle": "combo-sachet",
      "ref": "10045",
      "nombre": "COMBO SACHET",
      "categoria": "TOKENS",
      "tipo": "token",
      "precio": 15000,
      "precio_variable": false,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": 0,
        "Toberín": -12,
        "Bello": 0,
        "San Felipe": -88,
        "Perdomo": -43
      }
    },
    {
      "handle": "combo-shine",
      "ref": "10014",
      "nombre": "COMBO SHINE",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 3500,
      "precio_variable": false,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [
        {
          "ref": "10007",
          "cantidad": 1
        },
        {
          "ref": "10004",
          "cantidad": 1
        }
      ],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "destino-grande-(100-ml)",
      "ref": "10044",
      "nombre": "DESTINO PERFUM GRANDE",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 60000,
      "precio_variable": false,
      "costo": 42000,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": 0,
        "Toberín": 0,
        "Bello": 0,
        "San Felipe": 0,
        "Perdomo": 0
      }
    },
    {
      "handle": "destino-mediano-(40-ml)",
      "ref": "10042",
      "nombre": "DESTINO PERFUM MEDIANO",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 35000,
      "precio_variable": false,
      "costo": 24500,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": 1,
        "Toberín": 5,
        "Bello": 2,
        "San Felipe": 3,
        "Perdomo": 8
      }
    },
    {
      "handle": "destino-pequeño-(20ml)",
      "ref": "10040",
      "nombre": "DESTINO PERFUM PEQUEÑO",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 18000,
      "precio_variable": false,
      "costo": 12600,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": 2,
        "Toberín": 1,
        "Bello": 1,
        "San Felipe": 1,
        "Perdomo": 20
      }
    },
    {
      "handle": "fast-wax",
      "ref": "10003",
      "nombre": "FAST WAX",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 25000,
      "precio_variable": false,
      "costo": 10441,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 73,
        "Bolivariana": -2,
        "Toberín": -5,
        "Bello": 5,
        "San Felipe": 12,
        "Perdomo": -5
      }
    },
    {
      "handle": "fast-wax-250ml",
      "ref": "10031",
      "nombre": "FAST WAX 250ML",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 18000,
      "precio_variable": false,
      "costo": 6085,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 48,
        "Bolivariana": 7,
        "Toberín": 7,
        "Bello": 8,
        "San Felipe": 8,
        "Perdomo": 1
      }
    },
    {
      "handle": "impermeables",
      "ref": "10053",
      "nombre": "IMPERMEABLE",
      "categoria": "PRODUCTOS COMPLEMENTARIOS DE LAVADO",
      "tipo": "producto",
      "precio": 7000,
      "precio_variable": false,
      "costo": 4500,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": -1,
        "Bolivariana": 0,
        "Toberín": 0,
        "Bello": 0,
        "San Felipe": 0,
        "Perdomo": 0
      }
    },
    {
      "handle": "restaurador-partes-negras",
      "ref": "10061",
      "nombre": "MAGIC BLACK RESTORER",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 25000,
      "precio_variable": false,
      "costo": 5360,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 106,
        "Bolivariana": -23,
        "Toberín": 8,
        "Bello": -14,
        "San Felipe": 5,
        "Perdomo": -9
      }
    },
    {
      "handle": "manopla",
      "ref": "10022",
      "nombre": "MANOPLA ECONOMICA",
      "categoria": "PRODUCTOS COMPLEMENTARIOS DE LAVADO",
      "tipo": "producto",
      "precio": 7000,
      "precio_variable": false,
      "costo": 2000,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": 0,
        "Toberín": 0,
        "Bello": 0,
        "San Felipe": 0,
        "Perdomo": 0
      }
    },
    {
      "handle": "manopla-importada",
      "ref": "10049",
      "nombre": "MANOPLA IMPORTADA",
      "categoria": "PRODUCTOS COMPLEMENTARIOS DE LAVADO",
      "tipo": "producto",
      "precio": 12000,
      "precio_variable": false,
      "costo": 6000,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": -8,
        "Toberín": -5,
        "Bello": -5,
        "San Felipe": -8,
        "Perdomo": -3
      }
    },
    {
      "handle": "maquina-vending-bello",
      "ref": "10005",
      "nombre": "MAQUINA VENDING BELLO",
      "categoria": "SNACKS",
      "tipo": "producto",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "membresia-gold",
      "ref": "10013",
      "nombre": "MEMBRESIA GOLD",
      "categoria": "TOKENS",
      "tipo": "token",
      "precio": 60000,
      "precio_variable": false,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "membresia-silver",
      "ref": "10012",
      "nombre": "MEMBRESIA SILVER",
      "categoria": "TOKENS",
      "tipo": "token",
      "precio": 42000,
      "precio_variable": false,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "membresia-standart",
      "ref": "10008",
      "nombre": "MEMBRESIA STANDART",
      "categoria": "TOKENS",
      "tipo": "token",
      "precio": 24000,
      "precio_variable": false,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "monster",
      "ref": "10041",
      "nombre": "MONSTER",
      "categoria": "SNACKS",
      "tipo": "producto",
      "precio": 9500,
      "precio_variable": false,
      "costo": 5894,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": 2,
        "Toberín": -1,
        "Bello": 8,
        "San Felipe": -6,
        "Perdomo": 0
      }
    },
    {
      "handle": "desengrasante-1-l",
      "ref": "10018",
      "nombre": "MOTOR CLEANER",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 25000,
      "precio_variable": false,
      "costo": 3629,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 25,
        "Bolivariana": -2,
        "Toberín": -9,
        "Bello": 5,
        "San Felipe": 1,
        "Perdomo": -6
      }
    },
    {
      "handle": "motor-cleaner-250-ml",
      "ref": "10028",
      "nombre": "MOTOR CLEANER 250 ML",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 18000,
      "precio_variable": false,
      "costo": 2932,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 70,
        "Bolivariana": 8,
        "Toberín": 2,
        "Bello": 7,
        "San Felipe": -1,
        "Perdomo": 8
      }
    },
    {
      "handle": "ambientador",
      "ref": "10017",
      "nombre": "ODOR FRESH",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 14000,
      "precio_variable": false,
      "costo": 3657,
      "codigo_barras": "7709259378214",
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 157,
        "Bolivariana": 0,
        "Toberín": 0,
        "Bello": 1,
        "San Felipe": 0,
        "Perdomo": 0
      }
    },
    {
      "handle": "paquete-2.000",
      "ref": "10079",
      "nombre": "PAQUETE 2400",
      "categoria": "SNACKS",
      "tipo": "producto",
      "precio": 2400,
      "precio_variable": false,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": 0,
        "Toberín": 50,
        "Bello": 0,
        "San Felipe": -28,
        "Perdomo": 0
      }
    },
    {
      "handle": "paquete-2.500",
      "ref": "10080",
      "nombre": "PAQUETE 3000",
      "categoria": "SNACKS",
      "tipo": "producto",
      "precio": 3000,
      "precio_variable": false,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": 0,
        "Toberín": 15,
        "Bello": 0,
        "San Felipe": -25,
        "Perdomo": 0
      }
    },
    {
      "handle": "petit-x1",
      "ref": "10001",
      "nombre": "PETIT",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 6000,
      "precio_variable": false,
      "costo": 1500,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": -2,
        "Toberín": 8,
        "Bello": 8,
        "San Felipe": 33,
        "Perdomo": 32
      }
    },
    {
      "handle": "polishin-compound-copao",
      "ref": "10062",
      "nombre": "POLISHING COMPOUND",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 25000,
      "precio_variable": false,
      "costo": 4310,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 32,
        "Bolivariana": -2,
        "Toberín": 5,
        "Bello": 12,
        "San Felipe": 13,
        "Perdomo": 6
      }
    },
    {
      "handle": "productos-de-distribucion-12-oct",
      "ref": "10039",
      "nombre": "PRODUCTOS DISTRIBUCION 12 OCT",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "productos-distribucion-chia",
      "ref": "10011",
      "nombre": "PRODUCTOS DISTRIBUCION CHIA",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "productos-distribucion-itagui",
      "ref": "10038",
      "nombre": "PRODUCTOS DISTRIBUCION ITAGUI",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "productos-de-distribucion-la-union-1",
      "ref": "10050",
      "nombre": "PRODUCTOS DISTRIBUCION LA UNION",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "productos-distribucion-rionegro",
      "ref": "10051",
      "nombre": "PRODUCTOS DISTRIBUCION RIONEGRO",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "protectan-interior-250-ml",
      "ref": "10029",
      "nombre": "PROTECTAN INTERIOR 250 ML",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 18000,
      "precio_variable": false,
      "costo": 3474,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 57,
        "Bolivariana": 8,
        "Toberín": 9,
        "Bello": 10,
        "San Felipe": 7,
        "Perdomo": 8
      }
    },
    {
      "handle": "protectant-interior-cleaner.-limpiador-interiores",
      "ref": "10064",
      "nombre": "PROTECTANT INTERIOR CLEANER",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 25000,
      "precio_variable": false,
      "costo": 4801,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 42,
        "Bolivariana": -1,
        "Toberín": 4,
        "Bello": 14,
        "San Felipe": 6,
        "Perdomo": -5
      }
    },
    {
      "handle": "raspa-y-gana",
      "ref": "10055",
      "nombre": "RASPA Y GANA",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 1000,
      "precio_variable": false,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": 6,
        "Toberín": 332,
        "Bello": 124,
        "San Felipe": 99,
        "Perdomo": 387
      }
    },
    {
      "handle": "sachet-ultra-gloss",
      "ref": "10007",
      "nombre": "SACHET MAGIC BLACK",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 2500,
      "precio_variable": false,
      "costo": 410,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 790,
        "Bolivariana": 70,
        "Toberín": 72,
        "Bello": 57,
        "San Felipe": 59,
        "Perdomo": 97
      }
    },
    {
      "handle": "sachet-membresia",
      "ref": "10009",
      "nombre": "SACHET MEMBRESIA",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 0,
      "precio_variable": false,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": -17,
        "Toberín": 120,
        "Bello": 150,
        "San Felipe": 37,
        "Perdomo": 107
      }
    },
    {
      "handle": "sachet-ultragloss",
      "ref": "10004",
      "nombre": "SACHET ULTRAGLOSS",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 2500,
      "precio_variable": false,
      "costo": 387,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 2601,
        "Bolivariana": 36,
        "Toberín": 50,
        "Bello": 61,
        "San Felipe": 37,
        "Perdomo": 94
      }
    },
    {
      "handle": "servicio-tecnico-de-equipos",
      "ref": "10034",
      "nombre": "SERVICIO TECNICO TERCEROS",
      "categoria": "ADMINISTRATIVO",
      "tipo": "servicio",
      "precio": 0,
      "precio_variable": true,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "sio2-hybrid-wax",
      "ref": "10052",
      "nombre": "SiO2 HYBRID WAX",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 25000,
      "precio_variable": false,
      "costo": 9000,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": -10,
        "Toberín": 0,
        "Bello": 2,
        "San Felipe": 2,
        "Perdomo": 4
      }
    },
    {
      "handle": "super-combo-detailing",
      "ref": "10043",
      "nombre": "SUPER COMBO DETAILING",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 65000,
      "precio_variable": false,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [
        {
          "ref": "10003",
          "cantidad": 1
        },
        {
          "ref": "10061",
          "cantidad": 1
        },
        {
          "ref": "10063",
          "cantidad": 1
        },
        {
          "ref": "10020",
          "cantidad": 1
        },
        {
          "ref": "10019",
          "cantidad": 1
        }
      ],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "manzana",
      "ref": "10059",
      "nombre": "TOKEN",
      "categoria": "TOKENS",
      "tipo": "token",
      "precio": 6000,
      "precio_variable": false,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "token-parqueadero",
      "ref": "10006",
      "nombre": "TOKEN PARQUEADERO",
      "categoria": "TOKENS",
      "tipo": "token",
      "precio": 6000,
      "precio_variable": false,
      "costo": 0,
      "codigo_barras": null,
      "controla_stock": false,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": null,
        "Bolivariana": null,
        "Toberín": null,
        "Bello": null,
        "San Felipe": null,
        "Perdomo": null
      }
    },
    {
      "handle": "trapo-americano",
      "ref": "10020",
      "nombre": "TRAPO AMERICANO",
      "categoria": "PRODUCTOS COMPLEMENTARIOS DE LAVADO",
      "tipo": "producto",
      "precio": 8000,
      "precio_variable": false,
      "costo": 1898,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": -165,
        "Toberín": -64,
        "Bello": -90,
        "San Felipe": -68,
        "Perdomo": -39
      }
    },
    {
      "handle": "trapo-pequeño",
      "ref": "10019",
      "nombre": "TRAPO PEQUEÑO",
      "categoria": "PRODUCTOS COMPLEMENTARIOS DE LAVADO",
      "tipo": "producto",
      "precio": 4000,
      "precio_variable": false,
      "costo": 990,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 0,
        "Bolivariana": 12,
        "Toberín": -53,
        "Bello": 8,
        "San Felipe": 0,
        "Perdomo": 6
      }
    },
    {
      "handle": "ultra-gloos-tire-gel-.-gel-silicona",
      "ref": "10063",
      "nombre": "ULTRA GLOSS TIRE GEL",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 25000,
      "precio_variable": false,
      "costo": 4920,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": -4,
        "Bolivariana": -34,
        "Toberín": -10,
        "Bello": -7,
        "San Felipe": -3,
        "Perdomo": -4
      }
    },
    {
      "handle": "silicona-multiproposito",
      "ref": "10016",
      "nombre": "ULTRA SHINE PROTECT",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 25000,
      "precio_variable": false,
      "costo": 4205,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 14,
        "Bolivariana": -9,
        "Toberín": -7,
        "Bello": -14,
        "San Felipe": -7,
        "Perdomo": -11
      }
    },
    {
      "handle": "ultra-shine-protect-250-ml",
      "ref": "10030",
      "nombre": "ULTRA SHINE PROTECT 250 ML",
      "categoria": "PRODUCTOS PANZER CARWASH",
      "tipo": "producto",
      "precio": 18000,
      "precio_variable": false,
      "costo": 4205,
      "codigo_barras": null,
      "controla_stock": true,
      "iva": true,
      "componentes": [],
      "stock": {
        "Kemilabo": 60,
        "Bolivariana": 3,
        "Toberín": 1,
        "Bello": 1,
        "San Felipe": -2,
        "Perdomo": 11
      }
    }
  ]
};
